name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      run: |
        docker-compose up -d --build

#    - name: Run tests
#      run: docker-compose exec app go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Production
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        GIN_MODE: ${{ vars.GIN_MODE }}
      run: |
        docker-compose up -d --build
